config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'twitters#top'
  resources :twitters do
    collection do
      post :confirm
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/twitter.rb
class Twitter < ApplicationRecord
  validates :content, {presence: true, length:{maximum: 140}}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/twitters_controller.rb
class TwittersController < ApplicationController
  before_action :set_twitter, only: [:show, :edit, :update, :destroy]
  def top
  end
  def index
    @twitters = Twitter.all
  end
  def new
    @twitter = Twitter.new
  end
  def create
    @twitter = Twitter.new(twitter_params)
    if params[:back]
      render :new
    else
      if @twitter.save
        redirect_to twitters_path, notice: "つぶやきました！"
      else
        render :new
      end
    end
  end
  def show
  end
  def edit
  end
  def update
    if @twitter.update(twitter_params)
      redirect_to twitters_path, notice: "編集しました"
    else
      render :edit
    end
  end
  def destroy
    @twitter.destroy
    redirect_to twitters_path, notice:"削除しました"
  end
  def confirm
    @twitter = Twitter.new(twitter_params)
    render :new if @twitter.invalid?
  end
end
private
def twitter_params
  params.require(:twitter).permit(:content)
end
def set_twitter
  @twitter = Twitter.find(params[:id])
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twitters_helper.rb
module TwittersHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_twitters_path
    elsif action_name == 'edit'
      twitter_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <a>つぶやいてみよう</a>
    <a href="/">[トップページ]</a>
    <%= link_to '[一覧]', twitters_path %>
    <%= link_to '[新規投稿]', new_twitter_path %>
  </header>
  <body>
    <%= yield %>
  </body>
  <footer>
    <a>つぶやきツイート課題株式会社（注：架空）</a>
  </footer>
</html>

app/views/twitters/_form.html.erb
<!-- <h1>Twitters#_for</h1> -->
<%= form_with(model: @twitter, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @twitter.errors.any? %>
    <div>
      <h2><%= @twitter.errors.count %>件のエラーがあります</h2>
      <ul>
        <% @twitter.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to 'ツイッター一覧画面に戻る', twitters_path %>

app/views/twitters/confirm.html.erb
<!-- <h1>Twitters#confirm</h1> -->
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @twitter, url: twitters_path, local: true,) do |form| %>
<%# あくまでform_withメソッドなので、=form.//_fieldの入力フォームでは初期と同じく=でhtml上で表示させるが(でないとparameterが飛ばない)、改めて、hidden_fieldにて見えなくしている（値を書き換えられると確認の意味がないので）。そのため、別途、見えるだけの表示として、<= @twitter.content >がある。 %>
  <%= form.hidden_field :content %>
  <p>つぶやき内容<%= @twitter.content %></p>
  <%= form.submit "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/twitters/edit.html.erb
<!-- <h1>Twitters#edit</h1> -->
<h1>編集してみよう</h1>
<%= render 'form' %>

app/views/twitters/index.html.erb
<!-- <h1>Twitters#index</h1> -->
<h1>ツイッター一覧</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th>つぶやき内容</th>
  </tr>
  <% @twitters.each do |twitter| %>
  <tr>
    <td class="content"><%= twitter.content %></td>
    <td><%= link_to '詳細を確認する', twitter_path(twitter.id) %> </td>
    <td><%= link_to "編集する", edit_twitter_path(twitter.id) %></td>
    <td><%= link_to '削除する', twitter_path(twitter.id), method: :delete ,data: { confirm: '本当に削除していいですか？'} %></td>
  </tr>
<% end %>
</table>
<%= link_to '新しくつぶやく', new_twitter_path %>

app/views/twitters/new.html.erb
<!-- <h1>Twitters#new</h1> -->
<h1>新規投稿してみよう</h1>
<%= render 'form' %>

app/views/twitters/show.html.erb
<h1>詳細を確認してみよう</h1>
<p>つぶやき内容： <%= @twitter.content %></p>

app/views/twitters/top.html.erb
<h1>トップページ</h1>
<p>1字から140字までの投稿をつぶやけるサイトです</p>